spring:
  cloud:
    gateway:
      routes:
      - id: service-products
        uri: lb://service-products
        predicates:
          - Path=/api/product/**
        filters:
          - StripPrefix=2
          - name: Ejemplo
            args:
              mensaje: "Hola, Mensaje personalizado"
              cookieNombre: usuario
              cookieValor:  juliofhernandez
      - id: service-items
        uri: lb://service-items
        predicates:
          - Path=/api/item/**
        filters:
          - StripPrefix=2
